services:
  - type: web
    name: snap-food
    env: node
    buildCommand: npm install
    startCommand: node api-server/server.js
    envVars:
      - key: PORT
        value: 3000
      - key: OPENAI_API_KEY
        sync: false
    domains:
      - snap-food.onrender.com
      - deepseek-uhrc.onrender.com 